### ISSUE TITLE
Error with shinydashboardPlus-2.0.0 

### ISSUE THREAD

**Issue by vcognat** [OceaneCsn/DIANE#34]
Hi,

I had an error when I installed DIANE on my mac (R version 4.0.4) :
Error : object ‘boxPlus’ is not exported by 'namespace:shinydashboardPlus'

I solved the problem by installing an older version of shinydashboardPlus (0.75.5).

Have a nice day,

Valerie

**Comment by OceaneCsn** [comment]
Hi Valerie,

Thank you for your comment.  v2.0.0 is indeed a [breaking update of this package](https://rinterface.github.io/shinydashboardPlus/articles/shinydashboardPlus.html).
I'll specify the correct package versions or change the code to deal with that in the next update.
Enjoy your experience with DIANE and do not hesitate to give me any other feedback :)

Best regards,
Océane

**Comment by OceaneCsn** [comment]
It has been corrected, and should be installed from github without error now.

**Comment by vcognat** [comment]
I tried and it works ! Thanks a lot for your reactivity !

Best regards,

Valérie
