### ISSUE TITLE
command lines for each module

### ISSUE THREAD

**Issue by gorliver** [OceaneCsn/DIANE#39]
Is there a document to show the command lines used for each module?

**Comment by OceaneCsn** [comment]
Hi, the functions of DIANE are all described in [this reference](https://oceanecsn.github.io/DIANE/reference/index.html). An example of their use is available in [this vignette](https://oceanecsn.github.io/DIANE/articles/DIANE_Programming_Interface.html). Their usage in the shiny modules of the app can be browsed is in the R/ folder of the package source code (files with "module" in their names). 
To finish, if you download the HTML reports of your analysis in the app, you will get a number of the command lines used in your analysis (in the code sections), and also the settings that should allow you to re-run the all the command lines from a script, just as in the vignette.

**Comment by gorliver** [comment]
Great! Thank you for the documents!
