### ISSUE TITLE
Dose Response and Time Series Experiment Support

### ISSUE THREAD

**Issue by lloydtripp** [OceaneCsn/DIANE#41]
Does DIANE support dose-response or time-series experimental designs for analysis?

**Comment by OceaneCsn** [comment]
Thank you for this question. Continuous variables (like time or dose) are not properly modelled in DIANE. You can still run its pipeline with the different time points or doses as different conditions but this won't take full advantage of these gradual variables. If you are comfortable with using R scripts, DESEq2 or EdgeR allow more complex designs like dose-response or time-series. Here are some other useful R packages that come to mind to model time-series:
+ [moanin](https://www.bioconductor.org/packages/release/bioc/vignettes/moanin/inst/doc/documentation.html) (differential expression and co-expression analyses), 
+ [dynGENIE3](https://github.com/vahuynh/dynGENIE3)  or [Outpredict](https://github.com/jacirrone/OutPredict) (time-lagged Gene Regulatory Network inference)
Best regards!

**Comment by lloydtripp** [comment]
Thanks @OceaneCsn for the response! I'll look into the suggested packages.

I'd love to see this kind of feature in DIANE for those with complex experiments!
